spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/springwebapp
    username: admin
    password: admin778
  flyway:
    baseline-on-migrate: true
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.ws: DEBUG